--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO test;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO test;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO test;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO test;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO test;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO test;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO test;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO test;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO test;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO test;

--
-- Name: incident_detector_bruteforceincident; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.incident_detector_bruteforceincident (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    src_ip_address inet NOT NULL,
    username character varying(32) NOT NULL,
    reason text NOT NULL,
    attempts integer NOT NULL,
    "timeDelta" character varying(32) NOT NULL,
    successful integer NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL,
    incident_type character varying(16) NOT NULL
);


ALTER TABLE public.incident_detector_bruteforceincident OWNER TO test;

--
-- Name: incident_detector_bruteforceincident_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.incident_detector_bruteforceincident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_detector_bruteforceincident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_detector_concurrentloginincident; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.incident_detector_concurrentloginincident (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    src_ip_address inet NOT NULL,
    username character varying(32) NOT NULL,
    reason text NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL,
    incident_type character varying(16) NOT NULL
);


ALTER TABLE public.incident_detector_concurrentloginincident OWNER TO test;

--
-- Name: incident_detector_configincident; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.incident_detector_configincident (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    src_ip_address inet NOT NULL,
    username character varying(32) NOT NULL,
    reason text NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL,
    incident_type character varying(16) NOT NULL
);


ALTER TABLE public.incident_detector_configincident OWNER TO test;

--
-- Name: incident_detector_configincident_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.incident_detector_configincident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_detector_configincident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_detector_ddosincident; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.incident_detector_ddosincident (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    dst_ip_address inet NOT NULL,
    "timeDelta" character varying(32) NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL,
    incident_type character varying(16) NOT NULL,
    packets integer NOT NULL,
    protocol character varying(8) NOT NULL,
    reason text NOT NULL,
    sources text NOT NULL
);


ALTER TABLE public.incident_detector_ddosincident OWNER TO test;

--
-- Name: incident_detector_ddosincident_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.incident_detector_ddosincident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_detector_ddosincident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_detector_dosincident; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.incident_detector_dosincident (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    src_ip_address inet NOT NULL,
    dst_ip_address inet NOT NULL,
    "timeDelta" character varying(32) NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL,
    incident_type character varying(16) NOT NULL,
    packets integer NOT NULL,
    protocol character varying(8) NOT NULL,
    reason text NOT NULL
);


ALTER TABLE public.incident_detector_dosincident OWNER TO test;

--
-- Name: incident_detector_dosincident_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.incident_detector_dosincident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_detector_dosincident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_detector_loginincident_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.incident_detector_concurrentloginincident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_detector_loginincident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incident_detector_relatedlog; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.incident_detector_relatedlog (
    id bigint NOT NULL,
    bruteforce_incident_id bigint,
    concurrent_login_incident_id bigint,
    config_incident_id bigint,
    ddos_incident_id bigint,
    dos_incident_id bigint,
    netfilter_packet_id bigint,
    user_login_id bigint,
    user_logout_id bigint,
    usys_config_id bigint
);


ALTER TABLE public.incident_detector_relatedlog OWNER TO test;

--
-- Name: incident_detector_relatedlog_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.incident_detector_relatedlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_detector_relatedlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log_processor_netfilterpackets; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.log_processor_netfilterpackets (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    src_ip_address inet NOT NULL,
    dst_ip_address inet NOT NULL,
    protocol character varying(8) NOT NULL,
    event_type character varying(16) NOT NULL,
    count integer NOT NULL,
    severity character varying(16) NOT NULL
);


ALTER TABLE public.log_processor_netfilterpackets OWNER TO test;

--
-- Name: log_processor_netfilterpackets_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.log_processor_netfilterpackets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_processor_netfilterpackets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log_processor_uploadedlogfile; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.log_processor_uploadedlogfile (
    id bigint NOT NULL,
    filename character varying(255) NOT NULL,
    file_hash character varying(64) NOT NULL,
    source character varying(100) NOT NULL,
    uploaded_by character varying(150),
    uploaded_at timestamp with time zone NOT NULL,
    status character varying(16) NOT NULL,
    entries_created integer NOT NULL,
    incident_counts jsonb,
    incidents_created_total integer NOT NULL
);


ALTER TABLE public.log_processor_uploadedlogfile OWNER TO test;

--
-- Name: log_processor_uploadedlogfile_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.log_processor_uploadedlogfile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_processor_uploadedlogfile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log_processor_userlogin; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.log_processor_userlogin (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    username character varying(32) NOT NULL,
    src_ip_address inet NOT NULL,
    terminal character varying(4),
    result character varying(16) NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL
);


ALTER TABLE public.log_processor_userlogin OWNER TO test;

--
-- Name: log_processor_userlogin_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.log_processor_userlogin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_processor_userlogin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log_processor_userlogout; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.log_processor_userlogout (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    username character varying(32) NOT NULL,
    terminal character varying(4),
    result character varying(16) NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL
);


ALTER TABLE public.log_processor_userlogout OWNER TO test;

--
-- Name: log_processor_userlogout_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.log_processor_userlogout ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_processor_userlogout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: log_processor_usysconfig; Type: TABLE; Schema: public; Owner: test
--

CREATE TABLE public.log_processor_usysconfig (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "table" character varying(32) NOT NULL,
    action character varying(16) NOT NULL,
    key character varying(100),
    value text,
    condition character varying(64),
    terminal character varying(32) NOT NULL,
    result character varying(16) NOT NULL,
    event_type character varying(16) NOT NULL,
    severity character varying(16) NOT NULL
);


ALTER TABLE public.log_processor_usysconfig OWNER TO test;

--
-- Name: log_processor_usysconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: test
--

ALTER TABLE public.log_processor_usysconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_processor_usysconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: incident_detector_bruteforceincident incident_detector_bruteforceincident_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_bruteforceincident
    ADD CONSTRAINT incident_detector_bruteforceincident_pkey PRIMARY KEY (id);


--
-- Name: incident_detector_configincident incident_detector_configincident_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_configincident
    ADD CONSTRAINT incident_detector_configincident_pkey PRIMARY KEY (id);


--
-- Name: incident_detector_ddosincident incident_detector_ddosincident_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_ddosincident
    ADD CONSTRAINT incident_detector_ddosincident_pkey PRIMARY KEY (id);


--
-- Name: incident_detector_dosincident incident_detector_dosincident_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_dosincident
    ADD CONSTRAINT incident_detector_dosincident_pkey PRIMARY KEY (id);


--
-- Name: incident_detector_concurrentloginincident incident_detector_loginincident_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_concurrentloginincident
    ADD CONSTRAINT incident_detector_loginincident_pkey PRIMARY KEY (id);


--
-- Name: incident_detector_relatedlog incident_detector_relatedlog_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_relatedlog_pkey PRIMARY KEY (id);


--
-- Name: log_processor_netfilterpackets log_processor_netfilterpackets_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.log_processor_netfilterpackets
    ADD CONSTRAINT log_processor_netfilterpackets_pkey PRIMARY KEY (id);


--
-- Name: log_processor_uploadedlogfile log_processor_uploadedlogfile_file_hash_key; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.log_processor_uploadedlogfile
    ADD CONSTRAINT log_processor_uploadedlogfile_file_hash_key UNIQUE (file_hash);


--
-- Name: log_processor_uploadedlogfile log_processor_uploadedlogfile_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.log_processor_uploadedlogfile
    ADD CONSTRAINT log_processor_uploadedlogfile_pkey PRIMARY KEY (id);


--
-- Name: log_processor_userlogin log_processor_userlogin_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.log_processor_userlogin
    ADD CONSTRAINT log_processor_userlogin_pkey PRIMARY KEY (id);


--
-- Name: log_processor_userlogout log_processor_userlogout_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.log_processor_userlogout
    ADD CONSTRAINT log_processor_userlogout_pkey PRIMARY KEY (id);


--
-- Name: log_processor_usysconfig log_processor_usysconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.log_processor_usysconfig
    ADD CONSTRAINT log_processor_usysconfig_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: incident_detector_relatedl_concurrent_login_incident__4c40963a; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedl_concurrent_login_incident__4c40963a ON public.incident_detector_relatedlog USING btree (concurrent_login_incident_id);


--
-- Name: incident_detector_relatedlog_bruteforce_incident_id_e62e2cf3; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_bruteforce_incident_id_e62e2cf3 ON public.incident_detector_relatedlog USING btree (bruteforce_incident_id);


--
-- Name: incident_detector_relatedlog_config_incident_id_c6c55223; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_config_incident_id_c6c55223 ON public.incident_detector_relatedlog USING btree (config_incident_id);


--
-- Name: incident_detector_relatedlog_ddos_incident_id_b513dbef; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_ddos_incident_id_b513dbef ON public.incident_detector_relatedlog USING btree (ddos_incident_id);


--
-- Name: incident_detector_relatedlog_dos_incident_id_0ed8b159; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_dos_incident_id_0ed8b159 ON public.incident_detector_relatedlog USING btree (dos_incident_id);


--
-- Name: incident_detector_relatedlog_netfilter_packet_id_29b93cdf; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_netfilter_packet_id_29b93cdf ON public.incident_detector_relatedlog USING btree (netfilter_packet_id);


--
-- Name: incident_detector_relatedlog_user_login_id_29fc1453; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_user_login_id_29fc1453 ON public.incident_detector_relatedlog USING btree (user_login_id);


--
-- Name: incident_detector_relatedlog_user_logout_id_5b3525f6; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_user_logout_id_5b3525f6 ON public.incident_detector_relatedlog USING btree (user_logout_id);


--
-- Name: incident_detector_relatedlog_usys_config_id_da190d69; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX incident_detector_relatedlog_usys_config_id_da190d69 ON public.incident_detector_relatedlog USING btree (usys_config_id);


--
-- Name: log_processor_uploadedlogfile_file_hash_0a0d7196_like; Type: INDEX; Schema: public; Owner: test
--

CREATE INDEX log_processor_uploadedlogfile_file_hash_0a0d7196_like ON public.log_processor_uploadedlogfile USING btree (file_hash varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_bruteforce_incident__e62e2cf3_fk_incident_; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_bruteforce_incident__e62e2cf3_fk_incident_ FOREIGN KEY (bruteforce_incident_id) REFERENCES public.incident_detector_bruteforceincident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_concurrent_login_inc_4c40963a_fk_incident_; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_concurrent_login_inc_4c40963a_fk_incident_ FOREIGN KEY (concurrent_login_incident_id) REFERENCES public.incident_detector_concurrentloginincident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_config_incident_id_c6c55223_fk_incident_; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_config_incident_id_c6c55223_fk_incident_ FOREIGN KEY (config_incident_id) REFERENCES public.incident_detector_configincident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_ddos_incident_id_b513dbef_fk_incident_; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_ddos_incident_id_b513dbef_fk_incident_ FOREIGN KEY (ddos_incident_id) REFERENCES public.incident_detector_ddosincident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_dos_incident_id_0ed8b159_fk_incident_; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_dos_incident_id_0ed8b159_fk_incident_ FOREIGN KEY (dos_incident_id) REFERENCES public.incident_detector_dosincident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_netfilter_packet_id_29b93cdf_fk_log_proce; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_netfilter_packet_id_29b93cdf_fk_log_proce FOREIGN KEY (netfilter_packet_id) REFERENCES public.log_processor_netfilterpackets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_user_login_id_29fc1453_fk_log_proce; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_user_login_id_29fc1453_fk_log_proce FOREIGN KEY (user_login_id) REFERENCES public.log_processor_userlogin(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_user_logout_id_5b3525f6_fk_log_proce; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_user_logout_id_5b3525f6_fk_log_proce FOREIGN KEY (user_logout_id) REFERENCES public.log_processor_userlogout(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: incident_detector_relatedlog incident_detector_re_usys_config_id_da190d69_fk_log_proce; Type: FK CONSTRAINT; Schema: public; Owner: test
--

ALTER TABLE ONLY public.incident_detector_relatedlog
    ADD CONSTRAINT incident_detector_re_usys_config_id_da190d69_fk_log_proce FOREIGN KEY (usys_config_id) REFERENCES public.log_processor_usysconfig(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

