# Generated by Django 5.2 on 2025-05-18 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetfilterPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=10)),
                ('event_type', models.CharField(default='network packet', max_length=50)),
                ('severity', models.CharField(default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='unknown', max_length=100)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('terminal', models.CharField(blank=True, max_length=4)),
                ('result', models.CharField(max_length=20)),
                ('event_type', models.CharField(default='login', max_length=50)),
                ('severity', models.CharField(default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=4)),
                ('result', models.CharField(max_length=20)),
                ('event_type', models.CharField(default='logout', max_length=50)),
                ('severity', models.CharField(default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('table', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=20)),
                ('event_type', models.CharField(default='config change', max_length=50)),
                ('severity', models.CharField(default='normal', max_length=20)),
            ],
        ),
    ]
