# Generated by Django 5.2 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("username", models.CharField(max_length=100)),
                ("ipAddress", models.GenericIPAddressField()),
                ("result", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Usys_Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("message", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("condition", models.CharField(max_length=100)),
                ("terminal", models.CharField(max_length=100)),
                ("result", models.CharField(max_length=20)),
            ],
        ),
    ]
