# Generated by Django 5.2 on 2025-05-29 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetfilterPackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip_address', models.GenericIPAddressField()),
                ('dst_ip_address', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=8)),
                ('event_type', models.CharField(default='network packets', max_length=16)),
                ('count', models.IntegerField(default=0)),
                ('severity', models.CharField(default='normal', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='unknown', max_length=100)),
                ('uploaded_by', models.CharField(max_length=150, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=16)),
                ('entries_created', models.IntegerField(default=0)),
                ('incidents_created_total', models.IntegerField(default=0)),
                ('incident_counts', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=32)),
                ('src_ip_address', models.GenericIPAddressField()),
                ('terminal', models.CharField(max_length=4, null=True)),
                ('result', models.CharField(max_length=16)),
                ('event_type', models.CharField(default='login', max_length=16)),
                ('severity', models.CharField(default='normal', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=32)),
                ('terminal', models.CharField(max_length=4, null=True)),
                ('result', models.CharField(max_length=16)),
                ('event_type', models.CharField(default='logout', max_length=16)),
                ('severity', models.CharField(default='normal', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UsysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('table', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=16)),
                ('key', models.CharField(max_length=100, null=True)),
                ('value', models.TextField(null=True)),
                ('condition', models.CharField(max_length=64, null=True)),
                ('terminal', models.CharField(max_length=32)),
                ('result', models.CharField(max_length=16)),
                ('event_type', models.CharField(default='config change', max_length=16)),
                ('severity', models.CharField(default='normal', max_length=16)),
            ],
        ),
    ]
