# Generated by Django 5.2 on 2025-06-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlogfile',
            name='keycloakUser',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
