# Generated by Django 5.2 on 2025-04-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config_Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("userAuditID", models.IntegerField()),
                ("result", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Daemon_Start",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("userAuditID", models.IntegerField()),
                ("result", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Sys_Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("userAuditID", models.IntegerField()),
                ("syscallValue", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Sys_Config_Change",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("userAuditID", models.IntegerField()),
                ("result", models.CharField(max_length=20)),
            ],
        ),
    ]
