# Generated by Django 5.2 on 2025-04-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usys_config",
            name="message",
            field=models.CharField(max_length=255),
        ),
    ]
