# Generated by Django 5.2 on 2025-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netfilterpacket',
            old_name='destination_ip',
            new_name='dst_ip_address',
        ),
        migrations.RenameField(
            model_name='netfilterpacket',
            old_name='source_ip',
            new_name='src_ip_address',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='ip_address',
            new_name='src_ip_address',
        ),
        migrations.AlterField(
            model_name='userlogout',
            name='terminal',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
