# Generated by Django 5.2 on 2025-06-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0002_uploadedlogfile_keycloakuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedlogfile',
            name='keycloakUser',
        ),
    ]
