# Generated by Django 5.2 on 2025-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0002_rename_destination_ip_netfilterpacket_dst_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlogfile',
            name='entries_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedlogfile',
            name='incident_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uploadedlogfile',
            name='incidents_created_total',
            field=models.IntegerField(default=0),
        ),
    ]
