# Generated by Django 5.2 on 2025-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0003_uploadedlogfile_entries_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetfilterPackets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("source_ip", models.GenericIPAddressField()),
                ("destination_ip", models.GenericIPAddressField()),
                ("protocol", models.CharField(max_length=10)),
                (
                    "event_type",
                    models.CharField(default="network packets", max_length=50),
                ),
                ("count", models.IntegerField(default=0)),
                ("status", models.CharField(default="normal", max_length=20)),
            ],
        ),
    ]
