# Generated by Django 5.2.3 on 2025-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0003_remove_uploadedlogfile_keycloakuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfilterpackets',
            name='protocol',
            field=models.CharField(max_length=16),
        ),
    ]
