# Generated by Django 5.2 on 2025-04-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0003_alter_usys_config_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usys_config",
            name="value",
            field=models.CharField(max_length=255),
        ),
    ]
