# Generated by Django 5.2 on 2025-05-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0005_alter_relatedlog_netfilter_packet"),
        ("log_processor", "0004_netfilterpackets"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NetfilterPacket",
        ),
        migrations.RenameField(
            model_name="userlogin",
            old_name="severity",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="userlogout",
            old_name="severity",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="usysconfig",
            old_name="severity",
            new_name="status",
        ),
    ]
