# Generated by Django 5.2 on 2025-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0004_alter_usys_config_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usys_config",
            name="action",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="condition",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="key",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="message",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="result",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="terminal",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="value",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
