# Generated by Django 5.2 on 2025-04-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "log_processor",
            "0005_alter_usys_config_action_alter_usys_config_condition_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usys_config",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="condition",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="key",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="message",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="result",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="terminal",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usys_config",
            name="value",
            field=models.CharField(max_length=255),
        ),
    ]
