# Generated by Django 5.2 on 2025-05-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0005_delete_netfilterpacket_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="netfilterpackets",
            old_name="status",
            new_name="severity",
        ),
        migrations.RenameField(
            model_name="userlogin",
            old_name="status",
            new_name="severity",
        ),
        migrations.RenameField(
            model_name="userlogout",
            old_name="status",
            new_name="severity",
        ),
        migrations.RenameField(
            model_name="usysconfig",
            old_name="status",
            new_name="severity",
        ),
    ]
