# Generated by Django 5.2 on 2025-05-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0006_rename_status_netfilterpackets_severity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netfilterpackets',
            old_name='destination_ip',
            new_name='dst_ip_address',
        ),
        migrations.RenameField(
            model_name='netfilterpackets',
            old_name='source_ip',
            new_name='src_ip_address',
        ),
    ]
