# Generated by Django 5.2 on 2025-04-24 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "log_processor",
            "0006_alter_usys_config_action_alter_usys_config_condition_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user_login",
            name="session",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usys_config",
            name="session",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
