# Generated by Django 5.2 on 2025-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "log_processor",
            "0007_rename_destination_ip_netfilterpackets_dst_ip_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="netfilterpackets",
            name="event_type",
            field=models.CharField(default="network packets", max_length=16),
        ),
        migrations.AlterField(
            model_name="netfilterpackets",
            name="protocol",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="netfilterpackets",
            name="severity",
            field=models.CharField(default="normal", max_length=16),
        ),
        migrations.AlterField(
            model_name="uploadedlogfile",
            name="incident_counts",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedlogfile",
            name="status",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="uploadedlogfile",
            name="uploaded_by",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="event_type",
            field=models.CharField(default="login", max_length=16),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="result",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="severity",
            field=models.CharField(default="normal", max_length=16),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="terminal",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="username",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="userlogout",
            name="event_type",
            field=models.CharField(default="logout", max_length=16),
        ),
        migrations.AlterField(
            model_name="userlogout",
            name="result",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="userlogout",
            name="severity",
            field=models.CharField(default="normal", max_length=16),
        ),
        migrations.AlterField(
            model_name="userlogout",
            name="terminal",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="userlogout",
            name="username",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="action",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="condition",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="event_type",
            field=models.CharField(default="config change", max_length=16),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="key",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="result",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="severity",
            field=models.CharField(default="normal", max_length=16),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="table",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="terminal",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="usysconfig",
            name="value",
            field=models.TextField(null=True),
        ),
    ]
