# Generated by Django 5.2 on 2025-04-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0007_user_login_session_usys_config_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usys_config",
            old_name="message",
            new_name="table",
        ),
    ]
