# Generated by Django 5.2 on 2025-04-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0008_rename_message_usys_config_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_login",
            old_name="ipAddress",
            new_name="ip_address",
        ),
        migrations.RemoveField(
            model_name="usys_config",
            name="session",
        ),
    ]
