# Generated by Django 5.2 on 2025-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0009_rename_ipaddress_user_login_ip_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Logout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("username", models.CharField(max_length=100)),
                ("terminal", models.CharField(max_length=4)),
                ("session", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=20)),
            ],
        ),
    ]
