# Generated by Django 5.2 on 2025-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0010_user_logout"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_login",
            name="terminal",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
