# Generated by Django 5.2 on 2025-05-02 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0012_uploadedlogfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlogfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
