# Generated by Django 5.2 on 2025-05-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0013_alter_uploadedlogfile_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_login",
            name="session",
        ),
        migrations.RemoveField(
            model_name="user_logout",
            name="session",
        ),
    ]
