# Generated by Django 5.2 on 2025-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0014_remove_user_login_session_remove_user_logout_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlogfile',
            name='file_hash',
            field=models.CharField(default='TEMP_HASH', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
