# Generated by Django 5.2 on 2025-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0015_uploadedlogfile_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlogfile',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
