# Generated by Django 5.2 on 2025-05-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0016_alter_uploadedlogfile_uploaded_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetfilterPacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("source_ip", models.GenericIPAddressField()),
                ("destination_ip", models.GenericIPAddressField()),
                ("protocol", models.CharField(max_length=10)),
            ],
        ),
    ]
