# Generated by Django 5.2 on 2025-05-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_processor", "0017_netfilterpacket"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NetfilterPacket",
            new_name="NetfilterPkt",
        ),
    ]
