# Generated by Django 5.2 on 2025-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0018_rename_netfilterpacket_netfilterpkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='event_type',
            field=models.CharField(default='login', max_length=50),
        ),
        migrations.AddField(
            model_name='user_login',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_logout',
            name='event_type',
            field=models.CharField(default='logout', max_length=50),
        ),
        migrations.AddField(
            model_name='user_logout',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usys_config',
            name='event_type',
            field=models.CharField(default='config', max_length=50),
        ),
        migrations.AddField(
            model_name='usys_config',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
