# Generated by Django 5.2 on 2025-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0019_user_login_event_type_user_login_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netfilterpkt',
            name='event_type',
            field=models.CharField(default='paket_input', max_length=50),
        ),
        migrations.AddField(
            model_name='netfilterpkt',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
