# Generated by Django 5.2 on 2025-05-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0020_netfilterpkt_event_type_netfilterpkt_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfilterpkt',
            name='severity',
            field=models.CharField(default='paket_input', max_length=20),
        ),
    ]
