# Generated by Django 5.2 on 2025-05-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0021_alter_netfilterpkt_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfilterpkt',
            name='severity',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
