# Generated by Django 5.2 on 2025-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_processor', '0022_alter_netfilterpkt_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netfilterpkt',
            name='event_type',
            field=models.CharField(default='network paket', max_length=50),
        ),
        migrations.AlterField(
            model_name='usys_config',
            name='event_type',
            field=models.CharField(default='config change', max_length=50),
        ),
    ]
