# Generated by Django 5.2 on 2025-05-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_processor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("username", models.CharField(max_length=100)),
                ("src_ip_address", models.GenericIPAddressField()),
                ("dst_ip_address", models.GenericIPAddressField()),
                ("reason", models.TextField()),
                ("event_type", models.CharField(default="incident", max_length=50)),
                ("severity", models.CharField(default="critical", max_length=20)),
                ("incident_type", models.CharField(default="boese", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RelatedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_logs_set",
                        to="incident_detector.incident",
                    ),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_logs_set",
                        to="log_processor.uploadedlogfile",
                    ),
                ),
                (
                    "netfilter_packet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="log_processor.netfilterpacket",
                    ),
                ),
                (
                    "user_login",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="log_processor.userlogin",
                    ),
                ),
                (
                    "usys_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="log_processor.usysconfig",
                    ),
                ),
            ],
        ),
    ]
