# Generated by Django 5.2 on 2025-06-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BruteforceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timeDelta', models.CharField(max_length=32)),
                ('src_ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('event_type', models.CharField(default='incident', max_length=16)),
                ('severity', models.CharField(default='critical', max_length=16)),
                ('incident_type', models.CharField(default='bruteforce', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ConcurrentLoginIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('event_type', models.CharField(default='incident', max_length=16)),
                ('severity', models.CharField(default='critical', max_length=16)),
                ('incident_type', models.CharField(default='concurrentLogin', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip_address', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('event_type', models.CharField(default='incident', max_length=16)),
                ('severity', models.CharField(default='critical', max_length=16)),
                ('incident_type', models.CharField(default='configchange', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='DDosIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timeDelta', models.CharField(max_length=32)),
                ('dst_ip_address', models.GenericIPAddressField()),
                ('event_type', models.CharField(default='incident', max_length=16)),
                ('severity', models.CharField(default='critical', max_length=16)),
                ('incident_type', models.CharField(default='ddos', max_length=16)),
                ('packets', models.IntegerField(default=0)),
                ('protocol', models.CharField(max_length=8)),
                ('reason', models.TextField()),
                ('sources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DosIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timeDelta', models.CharField(max_length=32)),
                ('src_ip_address', models.GenericIPAddressField()),
                ('dst_ip_address', models.GenericIPAddressField()),
                ('event_type', models.CharField(default='incident', max_length=16)),
                ('severity', models.CharField(default='critical', max_length=16)),
                ('incident_type', models.CharField(default='dos', max_length=16)),
                ('packets', models.IntegerField(default=0)),
                ('protocol', models.CharField(max_length=8)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruteforce_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incident_detector.bruteforceincident')),
                ('concurrent_login_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incident_detector.concurrentloginincident')),
                ('config_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incident_detector.configincident')),
                ('ddos_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incident_detector.ddosincident')),
                ('dos_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incident_detector.dosincident')),
                ('netfilter_packet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_processor.netfilterpackets')),
                ('user_login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_processor.userlogin')),
                ('user_logout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_processor.userlogout')),
                ('usys_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_processor.usysconfig')),
            ],
        ),
    ]
