# Generated by Django 5.2 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_processor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("username", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("reason", models.TextField()),
                ("related_logs", models.ManyToManyField(to="log_processor.user_login")),
            ],
        ),
    ]
