# Generated by Django 5.2 on 2025-04-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0001_initial"),
        ("log_processor", "0009_rename_ipaddress_user_login_ip_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="related_logs",
            new_name="related_logins",
        ),
        migrations.AddField(
            model_name="incident",
            name="related_config_changes",
            field=models.ManyToManyField(to="log_processor.usys_config"),
        ),
    ]
