# Generated by Django 5.2 on 2025-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="dst_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
