# Generated by Django 5.2 on 2025-05-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip_address', models.GenericIPAddressField()),
                ('dst_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timeDelta', models.CharField(max_length=20)),
                ('event_type', models.CharField(default='incident', max_length=50)),
                ('severity', models.CharField(default='critical', max_length=20)),
                ('incident_type', models.CharField(default='dos', max_length=20)),
                ('packets', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=10)),
                ('reason', models.TextField()),
            ],
        ),
    ]
