# Generated by Django 5.2 on 2025-05-30 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0001_initial'),
        ('log_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruteforceincident',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_processor.uploadedlogfile'),
        ),
        migrations.AddField(
            model_name='relatedlog',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_processor.uploadedlogfile'),
        ),
    ]
