# Generated by Django 5.2 on 2025-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0002_dosincident'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDosIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('dst_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timeDelta', models.CharField(max_length=20)),
                ('event_type', models.CharField(default='incident', max_length=50)),
                ('severity', models.CharField(default='critical', max_length=20)),
                ('incident_type', models.CharField(default='ddos', max_length=20)),
                ('packets', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('sources', models.CharField(max_length=10)),
            ],
        ),
    ]
