# Generated by Django 5.2 on 2025-04-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incident_detector",
            "0002_rename_related_logs_incident_related_logins_and_more",
        ),
        ("log_processor", "0009_rename_ipaddress_user_login_ip_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="related_config_changes",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="related_logins",
        ),
        migrations.AddField(
            model_name="incident",
            name="related_logs",
            field=models.ManyToManyField(
                related_name="incident_related_logs", to="log_processor.user_login"
            ),
        ),
        migrations.CreateModel(
            name="RelatedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_logs_set",
                        to="incident_detector.incident",
                    ),
                ),
                (
                    "user_login",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_processor.user_login",
                    ),
                ),
                (
                    "usys_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_processor.usys_config",
                    ),
                ),
            ],
        ),
    ]
