# Generated by Django 5.2 on 2025-04-30 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0003_remove_incident_related_config_changes_and_more"),
        ("log_processor", "0009_rename_ipaddress_user_login_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="related_logs",
            field=models.ManyToManyField(to="log_processor.user_login"),
        ),
        migrations.CreateModel(
            name="Related_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_detector.incident",
                    ),
                ),
                (
                    "user_login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_processor.user_login",
                    ),
                ),
                (
                    "usys_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_processor.usys_config",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RelatedLog",
        ),
    ]
