# Generated by Django 5.2 on 2025-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0003_ddosincident'),
    ]

    operations = [
        migrations.CreateModel(
            name='BruteforceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('attempts', models.CharField(max_length=100)),
                ('timeDelta', models.CharField(max_length=20)),
                ('successful', models.CharField(max_length=20)),
                ('event_type', models.CharField(default='incident', max_length=50)),
                ('severity', models.CharField(default='critical', max_length=20)),
                ('incident_type', models.CharField(default='configchange', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('event_type', models.CharField(default='incident', max_length=50)),
                ('severity', models.CharField(default='critical', max_length=20)),
                ('incident_type', models.CharField(default='configchange', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoginIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('event_type', models.CharField(default='incident', max_length=50)),
                ('severity', models.CharField(default='critical', max_length=20)),
                ('incident_type', models.CharField(default='concurrentLogin', max_length=20)),
            ],
        ),
    ]
