# Generated by Django 5.2 on 2025-05-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0004_bruteforceincident_configincident_loginincident"),
        ("log_processor", "0004_netfilterpackets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedlog",
            name="netfilter_packet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="log_processor.netfilterpackets",
            ),
        ),
    ]
