# Generated by Django 5.2 on 2025-04-30 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0004_alter_incident_related_logs_related_log_and_more"),
        ("log_processor", "0009_rename_ipaddress_user_login_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="related_logs",
            field=models.ManyToManyField(
                related_name="incident_related_logs", to="log_processor.user_login"
            ),
        ),
        migrations.AlterField(
            model_name="related_log",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_logs_set",
                to="incident_detector.incident",
            ),
        ),
        migrations.AlterField(
            model_name="related_log",
            name="user_login",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="log_processor.user_login",
            ),
        ),
        migrations.AlterField(
            model_name="related_log",
            name="usys_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="log_processor.usys_config",
            ),
        ),
    ]
