# Generated by Django 5.2 on 2025-05-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0005_alter_incident_related_logs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="related_logs",
        ),
    ]
