# Generated by Django 5.2 on 2025-05-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0005_alter_relatedlog_netfilter_packet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoginIncident",
            new_name="ConcurrentLoginIncident",
        ),
    ]
