# Generated by Django 5.2 on 2025-05-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0006_remove_incident_related_logs'),
        ('log_processor', '0018_rename_netfilterpacket_netfilterpkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='related_log',
            name='log_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_logs_set', to='log_processor.uploadedlogfile'),
        ),
        migrations.AddField(
            model_name='related_log',
            name='netfilter_pkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_processor.netfilterpkt'),
        ),
    ]
