# Generated by Django 5.2 on 2025-05-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0006_rename_loginincident_concurrentloginincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddosincident',
            name='sources',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
