# Generated by Django 5.2 on 2025-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0007_alter_ddosincident_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddosincident',
            name='sources',
            field=models.CharField(max_length=255),
        ),
    ]
