# Generated by Django 5.2 on 2025-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0007_related_log_log_file_related_log_netfilter_pkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='event_type',
            field=models.CharField(default='incident', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
