# Generated by Django 5.2 on 2025-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0008_alter_ddosincident_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruteforceincident',
            name='incident_type',
            field=models.CharField(default='bruteforce', max_length=20),
        ),
    ]
