# Generated by Django 5.2 on 2025-05-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0008_incident_event_type_incident_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(default='critical', max_length=20),
        ),
    ]
