# Generated by Django 5.2 on 2025-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0009_alter_incident_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(default='boese', max_length=20),
        ),
    ]
