# Generated by Django 5.2 on 2025-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0009_alter_bruteforceincident_incident_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ddosincident",
            name="dst_ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ddosincident",
            name="event_type",
            field=models.CharField(default="incident", max_length=16),
        ),
        migrations.AlterField(
            model_name="ddosincident",
            name="incident_type",
            field=models.CharField(default="ddos", max_length=16),
        ),
        migrations.AlterField(
            model_name="ddosincident",
            name="packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ddosincident",
            name="protocol",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="ddosincident",
            name="severity",
            field=models.CharField(default="critical", max_length=16),
        ),
        migrations.AlterField(
            model_name="ddosincident",
            name="sources",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ddosincident",
            name="timeDelta",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="dosincident",
            name="dst_ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dosincident",
            name="event_type",
            field=models.CharField(default="incident", max_length=16),
        ),
        migrations.AlterField(
            model_name="dosincident",
            name="incident_type",
            field=models.CharField(default="dos", max_length=16),
        ),
        migrations.AlterField(
            model_name="dosincident",
            name="packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dosincident",
            name="protocol",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="dosincident",
            name="severity",
            field=models.CharField(default="critical", max_length=16),
        ),
        migrations.AlterField(
            model_name="dosincident",
            name="timeDelta",
            field=models.CharField(max_length=32),
        ),
    ]
