# Generated by Django 5.2 on 2025-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0010_alter_ddosincident_dst_ip_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatedlog",
            name="incident",
        ),
        migrations.RemoveField(
            model_name="relatedlog",
            name="log_file",
        ),
        migrations.RemoveField(
            model_name="relatedlog",
            name="netfilter_packet",
        ),
        migrations.RemoveField(
            model_name="relatedlog",
            name="user_login",
        ),
        migrations.RemoveField(
            model_name="relatedlog",
            name="usys_config",
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="event_type",
            field=models.CharField(default="incident", max_length=16),
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="incident_type",
            field=models.CharField(default="bruteforce", max_length=16),
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="severity",
            field=models.CharField(default="critical", max_length=16),
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="src_ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="successful",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="timeDelta",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="bruteforceincident",
            name="username",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="concurrentloginincident",
            name="event_type",
            field=models.CharField(default="incident", max_length=16),
        ),
        migrations.AlterField(
            model_name="concurrentloginincident",
            name="incident_type",
            field=models.CharField(default="concurrentLogin", max_length=16),
        ),
        migrations.AlterField(
            model_name="concurrentloginincident",
            name="severity",
            field=models.CharField(default="critical", max_length=16),
        ),
        migrations.AlterField(
            model_name="concurrentloginincident",
            name="src_ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="concurrentloginincident",
            name="username",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="configincident",
            name="event_type",
            field=models.CharField(default="incident", max_length=16),
        ),
        migrations.AlterField(
            model_name="configincident",
            name="incident_type",
            field=models.CharField(default="configchange", max_length=16),
        ),
        migrations.AlterField(
            model_name="configincident",
            name="severity",
            field=models.CharField(default="critical", max_length=16),
        ),
        migrations.AlterField(
            model_name="configincident",
            name="src_ip_address",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="configincident",
            name="username",
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name="Incident",
        ),
        migrations.DeleteModel(
            name="RelatedLog",
        ),
    ]
