# Generated by Django 5.2 on 2025-05-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_detector', '0010_detectionconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectionConfig',
        ),
    ]
