# Generated by Django 5.2 on 2025-05-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0011_remove_relatedlog_incident_and_more"),
        ("log_processor", "0008_alter_netfilterpackets_event_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bruteforce_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_detector.bruteforceincident",
                    ),
                ),
                (
                    "concurrent_login_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_detector.concurrentloginincident",
                    ),
                ),
                (
                    "config_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_detector.configincident",
                    ),
                ),
                (
                    "ddos_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_detector.ddosincident",
                    ),
                ),
                (
                    "dos_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_detector.dosincident",
                    ),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_processor.uploadedlogfile",
                    ),
                ),
                (
                    "netfilter_packet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="log_processor.netfilterpackets",
                    ),
                ),
                (
                    "user_login",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="log_processor.userlogin",
                    ),
                ),
                (
                    "user_logout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="log_processor.userlogout",
                    ),
                ),
                (
                    "usys_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="log_processor.usysconfig",
                    ),
                ),
            ],
        ),
    ]
