# Generated by Django 5.2 on 2025-05-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0012_relatedlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relatedlog",
            name="log_file",
        ),
    ]
