# Generated by Django 5.2 on 2025-05-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident_detector", "0013_remove_relatedlog_log_file"),
        ("log_processor", "0008_alter_netfilterpackets_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedlog",
            name="bruteforce_incident",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incident_detector.bruteforceincident",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="concurrent_login_incident",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incident_detector.concurrentloginincident",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="config_incident",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incident_detector.configincident",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="ddos_incident",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incident_detector.ddosincident",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="dos_incident",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incident_detector.dosincident",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="netfilter_packet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="log_processor.netfilterpackets",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="user_login",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="log_processor.userlogin",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="user_logout",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="log_processor.userlogout",
            ),
        ),
        migrations.AlterField(
            model_name="relatedlog",
            name="usys_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="log_processor.usysconfig",
            ),
        ),
    ]
