/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfigResultCounts { 
    'brute.force'?: number;
    critical_config_change?: number;
    concurrent_logins?: number;
    dos?: number;
    ddos?: number;
}

