/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigResult } from './configResult';
import { IncidentsConfigPostRequest } from './incidentsConfigPostRequest';


export interface Config { 
    message?: string;
    last_updated?: string;
    changed?: boolean;
    total_incidents?: number;
    result?: ConfigResult;
    config?: IncidentsConfigPostRequest;
}

