/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DdosPackets { 
    timestamp?: string;
    dst_ip_address?: string;
    protocol?: string;
    timeDelta?: string;
    Count?: number;
    Sources?: string;
}

