/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DosPackets { 
    timestamp?: string;
    timewindow?: number;
    protocol?: string;
    SourceipAddress?: string;
    DestinationipAddress?: string;
    Count?: number;
}

