/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Events { 
    id?: number;
    timestamp?: string;
    reason?: string;
    ipAddress?: string;
    action?: string;
    event_type?: string;
    result?: Events.ResultEnum;
    severity?: string;
}
export namespace Events {
    export const ResultEnum = {
        Successful: 'successful',
        Failed: 'failed'
    } as const;
    export type ResultEnum = typeof ResultEnum[keyof typeof ResultEnum];
}


