/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IncidentsConfigPostRequestDdos { 
    packet_threshold?: number;
    time_delta?: number;
    repeat_threshold?: number;
    min_sources?: number;
}

