/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncidentsConfigPostRequestDos } from './incidentsConfigPostRequestDos';
import { IncidentsConfigPostRequestBruteForce } from './incidentsConfigPostRequestBruteForce';
import { IncidentsConfigPostRequestDdos } from './incidentsConfigPostRequestDdos';


export interface IncidentsConfigPostRequest { 
    brute_force?: IncidentsConfigPostRequestBruteForce;
    dos?: IncidentsConfigPostRequestDos;
    ddos?: IncidentsConfigPostRequestDdos;
}

