/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogEntryIncidents { 
    id?: number;
    timestamp?: string;
    username?: string;
    ipAddress?: string;
    reason?: string;
}

