/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogEntryConfigChanges { 
    id?: number;
    timestamp?: string;
    table?: string;
    terminal?: string;
    action?: string;
    key?: string;
    value?: string;
    result?: LogEntryConfigChanges.ResultEnum;
}
export namespace LogEntryConfigChanges {
    export const ResultEnum = {
        Success: 'success',
        Failed: 'failed'
    } as const;
    export type ResultEnum = typeof ResultEnum[keyof typeof ResultEnum];
}


