/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogEntryLogin { 
    id?: number;
    log_type?: string;
    timestamp?: string;
    username?: string;
    ipAddress?: string;
    result?: LogEntryLogin.ResultEnum;
}
export namespace LogEntryLogin {
    export const ResultEnum = {
        Successful: 'successful',
        Failed: 'failed'
    } as const;
    export type ResultEnum = typeof ResultEnum[keyof typeof ResultEnum];
}


