/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogEntryLogin { 
    id?: number;
    log_type?: string;
    timestamp?: string;
    username?: string;
    ipAddress?: string;
    Terminal?: string;
    result?: LogEntryLogin.ResultEnum;
}
export namespace LogEntryLogin {
    export type ResultEnum = 'successful' | 'failed';
    export const ResultEnum = {
        Successful: 'successful' as ResultEnum,
        Failed: 'failed' as ResultEnum
    };
}


