/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogEntryConfigChanges { 
    id?: number;
    timestamp?: string;
    username?: string;
    ipAddress?: string;
    changedSettings?: Array<string>;
    result?: LogEntryConfigChanges.ResultEnum;
}
export namespace LogEntryConfigChanges {
    export type ResultEnum = 'successful' | 'failed';
    export const ResultEnum = {
        Successful: 'successful' as ResultEnum,
        Failed: 'failed' as ResultEnum
    };
}


