/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogEntryConfigChanges { 
    id?: number;
    timestamp?: string;
    username?: string;
    ipAddress?: string;
    changedSettings?: Array<string>;
    result?: LogEntryConfigChanges.ResultEnum;
}
export namespace LogEntryConfigChanges {
    export const ResultEnum = {
        Successful: 'successful',
        Failed: 'failed'
    } as const;
    export type ResultEnum = typeof ResultEnum[keyof typeof ResultEnum];
}


