/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogFile { 
    id?: number;
    filename?: string;
    source?: string;
    uploaded_by?: string;
    uploaded_at?: string;
    status?: LogFile.StatusEnum;
}
export namespace LogFile {
    export const StatusEnum = {
        Success: 'success',
        Error: 'error'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


