/**
 * Logfile API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LogFile { 
    filename?: string;
    status?: LogFile.StatusEnum;
}
export namespace LogFile {
    export type StatusEnum = 'success' | 'error';
    export const StatusEnum = {
        Success: 'success' as StatusEnum,
        Error: 'error' as StatusEnum
    };
}


