name: Docker Build and Push

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: ghcr.io/jastit00/IT-Sec-Projekt

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker image tags
        id: vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Login to Github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:frontend-latest
            ${{ env.IMAGE_REPOSITORY }}:frontend-${{ env.BRANCH_NAME }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: backend/
          push: true
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:backend-latest
            ${{ env.IMAGE_REPOSITORY }}:backend-${{ env.BRANCH_NAME }}